# Rubocop custom config file
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - db/**/*

# style and layout changes
Layout/IndentationStyle:
  EnforcedStyle: spaces

Layout/IndentationWidth:
  Width: 2

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# enable these in the future
Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false
